# Create a program that will play the “cows and bulls” game with the user. The game works like this:
#
# Randomly generate a 4-digit number. Ask the user to guess a 4-digit number. For every digit that the user
# guessed correctly in the correct place, they have a “cow”. For every digit the user guessed correctly in
# the wrong place is a “bull.” Every time the user makes a guess, tell them how many “cows” and “bulls” they have.
# Once the user guesses the correct number, the game is over. Keep track of the number of guesses the user makes
# throughout teh game and tell the user at the end.
#
# Say the number generated by the computer is 1038. An example interaction could look like this:
#
#   Welcome to the Cows and Bulls Game!
#   Enter a number:
#   >>> 1234
#   2 cows, 0 bulls
#   >>> 1256
#   1 cow, 1 bull
#   ...
# Until the user guesses the number.


from random import randint


def game():
    winning_number = str(randint(1000, 9999))
    # cows = 0
    # bulls = 0
    guesses = 0
    game_ended = False

    while game_ended is False:
        user_guess = input('Guess the number')
        cows = 0
        bulls = 0
        for i in winning_number:
            for j in user_guess:
                if i == j:
                    bulls += 1
                    break

        for j in [0, 1, 2, 3]:
            if winning_number[j] == user_guess[j]:
                cows += 1

        guesses += 1

        if cows == 4:
            game_ended = True
            print('Congratulations, you won winning number was: {}'.format(winning_number))

        print('Cows: {}, bulls: {}, guesses: {}'.format(cows, bulls, guesses))


game()
